#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@ if data.values.aws.auth.irsa.role:
#@overlay/match by=overlay.subset({"kind":"ServiceAccount", "metadata": {"name": "cert-manager"}})
#@overlay/match-child-defaults missing_ok=True
---
metadata:
  annotations:
    eks.amazonaws.com/role-arn: #@ data.values.aws.auth.irsa.role

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata": {"name": "cert-manager"}})
#@overlay/match-child-defaults missing_ok=True
---
spec:
  template:
    spec:
      securityContext:
        fsGroup: 1001
#@ end
