---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    kbld.k14s.io/images: |
      - origins:
        - resolved:
            tag: 1.5.3
            url: quay.io/failk8s/cert-manager-package:1.5.3
        url: quay.io/failk8s/cert-manager-package@sha256:0d90fd52bc21dc40762c5b4dd258246cb023810f397e5f542a18d6180372e2c7
  name: cert-manager.dev.failk8s.com.1.5.3
  namespace: kapp-controller-packaging-global
spec:
  refName: cert-manager.dev.failk8s.com
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
      fetch:
      - imgpkgBundle:
          image: quay.io/failk8s/cert-manager-package@sha256:0d90fd52bc21dc40762c5b4dd258246cb023810f397e5f542a18d6180372e2c7
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  version: 1.5.3
