---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    kbld.k14s.io/images: |
      - origins:
        - resolved:
            tag: 1.12.0
            url: quay.io/failk8s/cert-manager-package:1.12.0
        url: quay.io/failk8s/cert-manager-package@sha256:48cba279a5cc83d7d54e05a2951d5d280507411d7ee41bee58b92064dcaf5340
  name: cert-manager.dev.failk8s.com.1.12.0
spec:
  refName: cert-manager.dev.failk8s.com
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
      fetch:
      - imgpkgBundle:
          image: quay.io/failk8s/cert-manager-package@sha256:48cba279a5cc83d7d54e05a2951d5d280507411d7ee41bee58b92064dcaf5340
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  version: 1.12.0
