---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: quay.io/jetstack/cert-manager-cainjector:v1.13.2
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v1.13.2
          url: quay.io/jetstack/cert-manager-cainjector:v1.13.2
  image: quay.io/jetstack/cert-manager-cainjector@sha256:858fee0c4af069d0e87c08fd0943f0091434e05f945d222875fc1f3d36c41616
- annotations:
    kbld.carvel.dev/id: quay.io/jetstack/cert-manager-controller:v1.13.2
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v1.13.2
          url: quay.io/jetstack/cert-manager-controller:v1.13.2
  image: quay.io/jetstack/cert-manager-controller@sha256:9c67cf8c92d8693f9b726bec79c2a84d2cebeb217af6947355601dec4acfa966
- annotations:
    kbld.carvel.dev/id: quay.io/jetstack/cert-manager-webhook:v1.13.2
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v1.13.2
          url: quay.io/jetstack/cert-manager-webhook:v1.13.2
  image: quay.io/jetstack/cert-manager-webhook@sha256:0a9470447ebf1d3ff1c172e19268be12dc26125ff83320d456f6826c677c0ed2
kind: ImagesLock
