---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: quay.io/jetstack/cert-manager-cainjector:v1.13.3
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v1.13.3
          url: quay.io/jetstack/cert-manager-cainjector:v1.13.3
  image: quay.io/jetstack/cert-manager-cainjector@sha256:ac5154525f99bd0872671613741aac1b7dcb9c0df988571a7618155ddb6fabd2
- annotations:
    kbld.carvel.dev/id: quay.io/jetstack/cert-manager-controller:v1.13.3
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v1.13.3
          url: quay.io/jetstack/cert-manager-controller:v1.13.3
  image: quay.io/jetstack/cert-manager-controller@sha256:2121d4250f5734ee097df243507d06536fc264140dba3425045a825ef597c79d
- annotations:
    kbld.carvel.dev/id: quay.io/jetstack/cert-manager-webhook:v1.13.3
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v1.13.3
          url: quay.io/jetstack/cert-manager-webhook:v1.13.3
  image: quay.io/jetstack/cert-manager-webhook@sha256:f45b21f770bf4676c732f19e2ef17c34f46ac75873a5e0aa25703d808b2e5566
kind: ImagesLock
