---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: quay.io/jetstack/cert-manager-cainjector:v1.13.1
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v1.13.1
          url: quay.io/jetstack/cert-manager-cainjector:v1.13.1
  image: quay.io/jetstack/cert-manager-cainjector@sha256:72072d492b43d7fd4f818bdc1d7e617c3ccbfe27c46c57a29eb6991d13ede572
- annotations:
    kbld.carvel.dev/id: quay.io/jetstack/cert-manager-controller:v1.13.1
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v1.13.1
          url: quay.io/jetstack/cert-manager-controller:v1.13.1
  image: quay.io/jetstack/cert-manager-controller@sha256:6b83f55bd99e1824a73938ebd09f7cd7330cdeaf945036f7ecffa4553bc18f26
- annotations:
    kbld.carvel.dev/id: quay.io/jetstack/cert-manager-webhook:v1.13.1
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v1.13.1
          url: quay.io/jetstack/cert-manager-webhook:v1.13.1
  image: quay.io/jetstack/cert-manager-webhook@sha256:48ea4a77dfa793b11a1e9b724f63b3480abe87a91b63ed21fcc0e63972ea0c9f
kind: ImagesLock
